version: '3'

services:
    master:
        build: ./app_master
        ports:
            - "3000:3000"
            - "3001:3001"
    frontend:
        build: ./app_frontend
        ports:
            - "3040:3040"
        networks: 
            - client_Fr
        depends_on:
            - master
    lbq:
        build: ./app_lbq
        ports:
            - "3000"
            - "3020:3020"
            - "3021:3021"
            - "3022:3022"
        depends_on:
            - master
    queue:
        build: ./app_queue
        ports:
            - "3030"
            - "3031"
        depends_on:
            - lbq
    worker:
        build: ./app_worker
        networks: 
            - client_Fr
        depends_on:
            - queue
    client:
        build: ./app_client
        depends_on:
            - frontend
networks:
    client_Fr:
        driver: bridge
        external: true
    