version: '3'

services:
    master:
        build: ./app_master
        ports:
            - "3000"
            - "3001"
        networks: 
            client_Fr:
                ipv4_address: 172.28.0.2
    frontend:
        build: ./app_frontend
        ports:
            - "3040:3040"
        networks: 
            - client_Fr
        depends_on:
            - master
    lbq:
        build: ./app_lbq
        ports:
            - "3000"
            - "3020"
            - "3021"
            - "3022"
        networks: 
            - client_Fr
        depends_on:
            - master
    queue:
        build: ./app_queue
        ports:
            - "3030"
            - "3031"
        networks: 
            - client_Fr
        depends_on:
            - lbq
    worker:
        build: ./app_worker
        networks: 
            - client_Fr
        depends_on:
            - queue
networks:
    client_Fr:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/24
